FROM python:3.11-slim

# Environment setup
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install mysqlclient build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements.txt from root directory and install packages
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy backend source code into Docker
COPY backend backend

# Set working directory to backend
WORKDIR /app/backend

# Collect static files (for Django)
RUN python manage.py collectstatic --noinput

# Start Django app with Gunicorn
CMD ["gunicorn", "api.wsgi:application", "--bind", "0.0.0.0:8000"]
