# Generated by Django 5.1.7 on 2025-05-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='您的全名', max_length=100)),
                ('job_title', models.CharField(help_text='您目前的職稱或專業領域', max_length=100)),
                ('bio', models.TextField(help_text='一段關於您的簡短介紹')),
                ('skills_summary', models.TextField(help_text='您的主要技能概述 (例如：Python, Django, JavaScript, React)')),
                ('experience_summary', models.TextField(help_text='您的重要專案或工作經驗摘要')),
                ('hobbies', models.TextField(blank=True, help_text='您的興趣愛好', null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='您的聯絡 Email (可選)', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='標記此筆資料是否為當前使用的主要資訊')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '個人資訊',
                'verbose_name_plural': '個人資訊',
            },
        ),
    ]
