# Generated by Django 5.1.7 on 2025-05-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(help_text='Born in Seattle, raised in Taiwan, and currently based in Boston.'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='peter890176@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='experience_summary',
            field=models.TextField(help_text='Research Assistant, Institute of Health and Welfare Policy, Taipei, Taiwan'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='full_name',
            field=models.CharField(help_text='Yue Wen Peter Li', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='hobbies',
            field=models.TextField(blank=True, help_text='A programmer who loves coffee, cats, memes, and trading.', null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark this entry as the currently active primary information'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_title',
            field=models.CharField(help_text='Full Stack Developer/ Software Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='skills_summary',
            field=models.TextField(help_text='Python, Django, JavaScript, React)'),
        ),
    ]
