# Generated by Django 5.1.7 on 2025-05-28 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_personalinfo_options_alter_personalinfo_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Infos'},
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='additional_info',
            field=models.TextField(blank=True, help_text='A place for more detailed Q&A, personality traits, beliefs, and lifestyle details.', null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='experience_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Experience Summary'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Hobbies & Interests'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this the currently active persona information?', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='skills_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Skills Summary'),
        ),
    ]
